A=2

IF A=1 THEN PRINT "1" ELSE PRINT "11"
IF A=1 THEN
  PRINT "2"
  IF A=1 THEN PRINT "3" ELSE PRINT "33"
  IF A=1 THEN
    PRINT "4"
    IF A=1 THEN PRINT "5"
  ELSE
    PRINT "6"
    IF A=1 THEN PRINT "7" ELSE PRINT "77"
  END IF
ELSE IF A=2 THEN
  PRINT "X"
  IF A<>2 THEN PRINT "XX" ELSE PRINT "XXX"
ELSE
  PRINT "8"
  IF A=1 THEN PRINT "9" ELSE PRINT "99"
END IF
