DO
CLS
FOR P=0 TO 1
IF BUTTON TAP(P,0) THEN TEXT 0,0,"A"+STR$(P)
IF BUTTON TAP(P,1) THEN TEXT 0,1,"B"+STR$(P)
IF UP TAP(P) THEN TEXT 0,2,"UP"+STR$(P)
IF DOWN TAP(P) THEN TEXT 0,3,"DOWN"+STR$(P)
IF LEFT TAP(P) THEN TEXT 0,4,"LEFT"+STR$(P)
IF RIGHT TAP(P) THEN TEXT 0,5,"RIGHT"+STR$(P)
IF TAP THEN TEXT 0,6,"TAP"
NEXT P
WAIT VBL
LOOP
