REM LITTLE TEST PROGRAM
PRINT "HELLO"
PRINT 1+3+2+5+4

A=1
B=0

IF NOT A=1 AND B=1 THEN PRINT "OK" ELSE PRINT "NO"
IF A=1 AND NOT B=1 THEN PRINT "OK" ELSE PRINT "NO"
IF NOT B=1 AND A=1 THEN PRINT "OK" ELSE PRINT "NO"
IF B=1 AND NOT A=1 THEN PRINT "OK" ELSE PRINT "NO"

END
